---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Core:
    - Arcane:
        href: http://arcane.home.lan
        description: Docker management UI.
    - Pi-hole:
        href: http://pihole.home.lan/admin
        description: DNS filtering and local DNS records.
    - Nginx Proxy Manager:
        href: http://npm.home.lan
        description: Reverse proxy and SSL certificate management.

- Code:
    - Gitea:
        href: http://gitea.home.lan
        description: Self-hosted Git service.
    - Code-Server:
        href: http://code.home.lan
        description: Online code editor (VS Code).

- Media:
    - Jellyfin:
        href: http://jellyfin.home.lan
        description: Media server for streaming movies, TV, music, and more.
