---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Home Server

layout:
  Core:
    style: column
    # columns: 3
  Code:
    style: column
    # columns: 3
  Media:
    style: column
    # columns: 3
  Docs:
    style: row
    columns: 3
