services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/prash/MyPC/home-server/volumes/portainer:/data
    networks:
      - home-server
      
networks:
  home-server:
    name: home-server
    driver: bridge
  backend:
    name: backend
    driver: bridge
