services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - homepage_config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./resources/thehomepage-custom-images:/app/public/images:ro
    environment:
      HOMEPAGE_ALLOWED_HOSTS: localhost,127.0.0.1,${HOST_IP},home-server.apps,home.lan
    networks:
      - home-server
      - proxy

networks:
  home-server:
    name: home-server
    driver: bridge
  proxy:
    name: proxy
    driver: bridge

volumes:
  homepage_config:
    name: homepage_config
  homepage_images:
    name: homepage_images